### ISSUE TITLE
Node.js v15 compatibility?

### ISSUE THREAD

**Issue by MichalCz** [ai/check-dts#11]
Hey,

I'm getting an interesting error while checking the types using node.js v15 (runtime, not `@types/node`).

To run the check in node v14 you can do this:

```
git clone https://github.com/signicode/scramjet.git
cd scramjet
npm ci
cd .d.ts
npx check-dts
```

This works and checks all the data, but when I change the node version to 15 (for instance `nvm i 15 && nvm use 15`).

```
/workspace/scramjet/.d.ts [develop|✚ 1] 
11:17 $ npx check-dts index.d.ts
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /workspace/scramjet/.d.ts/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/workspace/scramjet/.d.ts/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

**Comment by ai** [comment]
Everything is OK on my system (Fedora 32) on Node.js 15.0.1.

Can you try to re-install dependencies `rm -R node_modules && npm install`?

**Comment by MichalCz** [comment]
Yeah, doesn't help (`npm ci` does that BTW)... :/

Have you tried it on scramjet perhaps? I wonder why it tries to find the `package.json` there - any thoughts?

**Comment by ai** [comment]
Can you try calling `check-dts` from the project root? You do not need to move to `.d.ts/` folder.

**Comment by MichalCz** [comment]
Then the check-dts checks seems to test files that should not be checked I guess... I get this error, no matter what the node version is:

```
npx check-dts
⠦ Check typesTypeError: Cannot read property 'text' of undefined
    at check (/workspace/scramjet/node_modules/check-dts/check.js:107:43)
    at async run (/workspace/scramjet/node_modules/check-dts/bin.js:32:18)
npm ERR! code 1
npm ERR! path /workspace/scramjet
npm ERR! command failed
npm ERR! command sh -c check-dts

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2020-10-27T11_56_46_567Z-debug.log
```

**Comment by ai** [comment]
Try to rename dir to something without `.` in the beginning.

Sorry, I am spending my time on other open source projects right. I can debug your project. But I will be glad for PR.

**Comment by MichalCz** [comment]
Ok, I'll try to understand what's going on and I'll try to help out here.

**Comment by MichalCz** [comment]
What would you think of adding an option to pass globs in `process.argv[2]` and so on?

**Comment by ai** [comment]
Yeap, it will be nice
