### ISSUE TITLE
Error when project has JavaScript files

### ISSUE THREAD

**Issue by vasilii-kovalev** [ai/check-dts#24]
If a project has JavaScript files (`jest.config.js`, for example), they are used in the check as well as TypeScript ones, which leads to errors.
This pattern includes the JavaScript files:
https://github.com/ai/check-dts/blob/c3ceea25aab9603c0a704126dfc7cd74401d1097/check.js#L67
`all` variable contains the files because of the pattern:
https://github.com/ai/check-dts/blob/c3ceea25aab9603c0a704126dfc7cd74401d1097/check.js#L81
Then, the library tries to get errors from the files:
https://github.com/ai/check-dts/blob/c3ceea25aab9603c0a704126dfc7cd74401d1097/check.js#L99
And inevitably fails at this point:
https://github.com/ai/check-dts/blob/c3ceea25aab9603c0a704126dfc7cd74401d1097/check.js#L110
The error message is "TypeError: Cannot read property 'text' of undefined".

**Comment by vasilii-kovalev** [comment]
By the way, what the reason to have JavaScript files included?

**Comment by vasilii-kovalev** [comment]
I see, that CLI can accept some parameters like `--version`, `--help` and `globs` pattern, which is not described in the docs.

In my case, the problem is solved this way:
```shell
check-dts **/*.ts
```

**Comment by ai** [comment]
> By the way, what the reason to have JavaScript files included?

Because TS can be useful to find errors in JS files too.

> TypeError: Cannot read property 'text' of undefined

Do you have stacktrace? Seems like it is JS error somewhere not type checking error.

**Comment by vasilii-kovalev** [comment]
> Do you have stacktrace? Seems like it is JS error somewhere not type checking error.

```shell
TypeError: Cannot read property 'text' of undefined
    at check (file:///D:/Projects/active/hydrate-text/node_modules/check-dts/check.js:110:44)
    at async run (file:///D:/Projects/active/hydrate-text/node_modules/check-dts/bin.js:24:18)
```

**Comment by ai** [comment]
Perfect. I will try to fix it tomorrow.

**Comment by ai** [comment]
If you want, you can try to send PR

**Comment by vasilii-kovalev** [comment]
Actually, as I mentioned earlier, I just excluded JavaScript files via CLI arguments.
Maybe I will create a pull request with updated docs to describe CLI abilities.

**Comment by vasilii-kovalev** [comment]
By the way, it seems that non-TypeScript files have `file` assigned to `undefined`.
This line returns the following structures for TypeScript and non-TypeScript files.
https://github.com/ai/check-dts/blob/c3ceea25aab9603c0a704126dfc7cd74401d1097/create-program.js#L42

```
[
  // Non-TypeScript file (JS, JSON, etc.)
  {
    file: undefined,
    start: undefined,
    length: undefined,
    code: 6054,
    category: 1,
    messageText: [Object],
    relatedInformation: undefined
  },
  // index.errors.ts
  {
    file: [SourceFileObject],
    start: 173,
    length: 13,
    messageText: 'Expected 1-3 arguments, but got 0.',
    category: 1,
    code: 2554,
    reportsUnnecessary: undefined,
    reportsDeprecated: undefined,
    relatedInformation: [Array]
  }
]
```

So it seems, there is a hidden problem out there anyway.
Because I don't know, how the program should behave, I didn't change source code in #25.

**Comment by vasilii-kovalev** [comment]
I investigated TypeScript's `createProgram` code.
* On this line we get supported extensions depending on given compiler options.
https://github.com/microsoft/TypeScript/blob/42915c35299a79dc132bbb77e70f558a2b93a04d/src/compiler/program.ts#L836
* If the given files have unsupported extensions, an error with the text described in my previous message in this issue is thrown.
https://github.com/microsoft/TypeScript/blob/42915c35299a79dc132bbb77e70f558a2b93a04d/src/compiler/program.ts#L2433
* In our case, only these lines in `getSupportedExtensions` will be executed.
https://github.com/microsoft/TypeScript/blob/42915c35299a79dc132bbb77e70f558a2b93a04d/src/compiler/utilities.ts#L6685-L6689
* According to `getAllowJSCompilerOption` implementation, JavaScript files are allowed only if `allowJs` or `checkJs` are set to `true`. Otherwise, only TypeScript files are supported.
https://github.com/microsoft/TypeScript/blob/42915c35299a79dc132bbb77e70f558a2b93a04d/src/compiler/utilities.ts#L6151-L6153

And since my `tsconfig.json` doesn't have these files (because I have no JavaScript source files, and I'm not going to check them), but the default `globs` includes `js` extension, the check fails.

**Comment by ai** [comment]
What do you think if we will just ignore files without `i.file`? e17af59

Another option is to check `i.messageText.code`, but I do not know where to find the format.

**Comment by vasilii-kovalev** [comment]
[Link to the interface of the `i.textMessage`](https://github.com/microsoft/TypeScript/blob/52af8bf70f4992e5c862f1d1023561e95a0e59b8/lib/typescript.d.ts#L2772-L2777).
Codes are described in [`diagnosticMessages.json` file](https://github.com/microsoft/TypeScript/blob/main/src/compiler/diagnosticMessages.json). In our case, the error code is [6054](https://github.com/microsoft/TypeScript/blob/52af8bf70f4992e5c862f1d1023561e95a0e59b8/src/compiler/diagnosticMessages.json#L4214-L4217).

Ignoring `i.file` if it is `undefined` should help people like me, that don't have JavaScript files in their source code.
But I don't know how people setup "JavaScript + TypeScript declaration files" projects. If the people set `allowJs` or `checkJs` to `true`, so there should be no problems as well, I suppose.

**Comment by ai** [comment]
Fixed 36429e8

**Comment by ai** [comment]
The fix was released in 0.5.5

**Comment by vasilii-kovalev** [comment]
It seems the conditions are duplicated :)
https://github.com/ai/check-dts/blob/1b3d06eae40e3b2a430c98c79c1a7486fe28a48e/check.js#L108
Maybe there should be something else after `||`?

**Comment by ai** [comment]
The codes are different (6**50**4 || 6**05**4). One is for JS without `allowJs`. Another for non-JS unsupported code (like JSON).
