### ISSUE TITLE
'extends' option does not supported

### ISSUE THREAD

**Issue by bijela-gora** [ai/check-dts#28]
More info about `extends`: https://www.typescriptlang.org/tsconfig#extends

How to reproduce.
1. check out to https://github.com/Evercoder/culori/pull/166/commits/f50f7e7d48e6e4ddaf843d2b81172b4094e30557#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0R2
2. run `npm run check:dts`
3. command should fail with multiple errors
4. inline `"extends": "@tsconfig/node16-strictest/tsconfig.json",` config like here https://github.com/Evercoder/culori/pull/166/commits/513e60672d37667d8b10ebf895ee545aba2a3f15#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0
5. run `npm run check:dts`
6. command should finish successfully

**Comment by ai** [comment]
Please, send PR. I will not have time for it in next months.

**Comment by myshov** [comment]
@ai hi!
I think this issue can be closed already
