### ISSUE TITLE
Checking IntelliSense?

### ISSUE THREAD

**Issue by tommy-mitchell** [ai/check-dts#29]
The README mentions that positive tests can be used to check IntelliSense:

> You can test IDE autocompletion in this file.

Is there a way to do so? It could be convenient to have something like:

```ts
// from index.d.ts
declare function foo<T>(bar: T): T;

// in index.types.ts

const baz = foo(1);

// EXPECTS type number
type test = typeof baz;
```

Just some way to have an expected (positive) value. Similarly, a way to check JSDoc comments on `foo()` would be nice. Not sure how feasible these are.

**Comment by ai** [comment]
Not automatically. You can test it while you are writing them :D.

**Comment by tommy-mitchell** [comment]
To clarify, is this something that’s possible but not currently supported, or something that isn’t possible in general? I’d like to be able to test these things explicitly. Happy to help with a PR if so.

**Comment by ai** [comment]
> To clarify, is this something that’s possible but not currently supported, or something that isn’t possible in general?

I have no idea how to automate it

**Comment by tommy-mitchell** [comment]
Seems like the [TypeScript compiler API](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API#re-printing-sections-of-a-typescript-file) can be used:

```ts
// program from ts.createProgram()
const sourceFile = program.getSourceFile(file);
const checker = program.getTypeChecker();

type Nodes = [string, ts.Node];
const variables: Nodes[] = sourceFile.getChildren().map(node => [node.name.text, node]);

variables.forEach([name, node] => {
  const symbol = checker.getSymbolAtLocation(node.name);

  console.log(`comment: ${ ts.displayPartsToString(symbol.getDocumentationComment(checker)) }`);
  console.log(`type: ${ checker.typeToString(checker.getTypeOfSymbolAtLocation(symbol, symbol.valueDeclaration)) }`);
});
```

If the input is:

```ts
/** Hello, World! */
const foo: string = 'bar';
```

Then the parsed output would be:

```
comment: Hello, World!
type: string
```

**Comment by ai** [comment]
How do you see test file?

**Comment by tommy-mitchell** [comment]
https://github.com/ai/check-dts/blob/c22b3a0b2bf112d9cc1d9ed9646b63c4fd7c2934/create-program.js#L24-L43

You could do something like:

```js
const program = ts.createProgram(files, opts);

files.forEach(file => {
  program.getSourceFile(file);

  // do checks for “// EXPECT”
});
```

**Comment by ai** [comment]
Can you show how the test file (which will test the types) will looks like?

**Comment by tommy-mitchell** [comment]
It could look something like this:

```ts
// index.d.ts

/** FooBar */
export const foo = (bar: string) => bar;
```
```ts
// index.types.ts

import { foo  } from "index";

// EXPECT TYPE string
const foobar = foo("bar");

// EXPECT COMMENT FooBar 
foo("baz");
```

---

However, I've also since come across the [`tsd` library](https://github.com/SamVerschueren/tsd) which already has fine-grained `expect type` assertion. I've [submitted a PR](https://github.com/SamVerschueren/tsd/pull/155) to it for doc comments.

That said, I do appreciate the simplicity of `check-dts` and I like that the error assertions are more descriptive in this library. Given that other libraries already have more static assertions for types (`tsd`, [`tsd-lite`](https://github.com/mrazauskas/tsd-lite), [`expect-type`](https://www.npmjs.com/package/expect-type), [`dtslint`](https://github.com/microsoft/DefinitelyTyped-tools/tree/master/packages/dtslint), [`conditional-type-checks`](https://github.com/dsherret/conditional-type-checks), etc.), I'm not sure if it's in scope for `check-dts` to try to add something like `// EXPECT` as well. It could be convenient for simple cases, but it's up to you if that's worth the hassle. Feel free to close this issue if it's not.

**Comment by ai** [comment]
I think `expectType` from some type expect library is the best option
