### ISSUE TITLE
Duplicated if statements

### ISSUE THREAD

**Issue by stnrepin** [ai/check-dts#3]
There're duplicated if statements in the file check.js:

https://github.com/ai/check-dts/blob/463a1ea99072dc4ee4be8efbe3a84383e616bde5/check.js#L144-L167

Or:
```js
if (failed) {
 // A
} else {
 // B
}
if (!failed) {
 // C
} else {
 // D
}
```

This construction looks strange because blocks A, D and B,C can be easily combined (and I think it will make the code more readable). Or are there some reasons for such a decision?

**Comment by ai** [comment]
Good idea. Do you want to send PR?

**Comment by stnrepin** [comment]
Yes, I would be grateful for this opportunity. I'll send it in a minute.
