### ISSUE TITLE
Shows `undefined` instead of list of errors

### ISSUE THREAD

**Issue by coderaiser** [ai/check-dts#38]
`check-dts` shows `undefined`:

![image](https://github.com/ai/check-dts/assets/1573141/abae9f8c-904c-4bf0-9c05-97a2a37f7aef)

When I run it in this repository: https://github.com/putoutjs/babel.
Here is errors file [`test/errors.ts`](https://github.com/putoutjs/babel/blob/master/test/errors.ts).

```sh
npm i
npm run build
npm run test:dts
```

**Comment by ai** [comment]
Please send PR. Sorry, I don’t have time right now for investigation.

**Comment by coderaiser** [comment]
Looks like the reason is naming.
