### ISSUE TITLE
Any recommendation on checking the return value?

### ISSUE THREAD

**Issue by franciscop** [ai/check-dts#40]
Do you have any recommendation on how to check that the return value type is correct? For example, let's say my method `db.add()` returns a string id inside a promise:

```ts
// How to ensure "id" is a string?
const id = await db.add(...);

// Current check, use a String-exclusive method:
id.startsWith('abc');

// (fails, as expected)
id.toFixed(2);

// Does not fail unfortunately
assert(typeof id === 'string');
```

What I'm doing right now is calling the type-specific method to check that it works, but is there a better/recommended way to do this? Thanks!

**Comment by ai** [comment]
There are special libraries on npm for that.

But I don’t use it and have something like:

```js
let test: string = id
```

**Comment by franciscop** [comment]
Ah that makes a lot of sense, thanks! That works perfectly (as expected, warning when using the wrong type):

<img width="606" alt="image" src="https://github.com/ai/check-dts/assets/2801252/7c29a0be-f487-436a-9d7a-a4a0105b3be0">

Do you want me to do a PR adding this as an example? Maybe in the FAQ? Closing for now since it's solved

**Comment by ai** [comment]
Sure, good idea. Let’s add it to docs.
